### PR TITLE
Real device support

### PR DESCRIPTION
**Pull request by tasleson**
Changes to support working with real devices, preliminary changes.

### CODE REVIEW

**Comment by mulkieran** [comment]
Might as well break unrelated commits out into separate PRs, for easier review.

**Comment by mulkieran** [comment]
lint failures are real.

**Comment by tasleson** [comment]
> lint failures are real.

Yes they are, because I added another parameter to `make_class` and this PR is using master, not the branch that I added the change to.

I'm not sure how we want to stage changes that occur across repos?  I guess I could wait until any depend changes are merged before doing a PR that uses it?  One of the downsides of having 12 different repositories for a single project.

**Comment by mulkieran** [comment]
> I'm not sure how we want to stage changes that occur across repos? I guess I could wait until any depend changes are merged before doing a PR that uses it? One of the downsides of having 12 different repositories for a single project.

Rust and Python are different. For Rust, you can simply redirect the dependency in Cargo.toml to whatever branch you have made publicly available that uses the change you need. You can find many examples of that in our repos right now. For Python things are not so convenient. I think you would have to package your change and post it somewhere, which is a pain, so I do not go to the trouble.

Most of the commits in this particular PR do not depend on the PR in ```dbus-python-client-gen```. So, you can split them out into a separate PR for faster merging, especially as they are not very strongly related to each other.

**Pull request closed without merging**
